name: pruandprue.com
favicon: null
layout_spectrum: 0.96557
typography_spectrum: 0.676
title: 'resourceful, edgy, determined and endlessly surprising '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f1e5'
    - '#d1c3a6'
    - '#5b4837'
    - '#060100'
    - '#8c7a62'
  brandStrength: 0.1875
  lightness: 0.8517782764974982
  saturation: 0.5625
  rhythmicContrast: 0.3769118287600577
purpose: []
